version: "3"
services:
    api:
      #build: ./ClassroomScheduler
      image: "acestojanoski/classroomscheduler:v1"
      ports:
        - "5000:80"
      depends_on:
        - db
    db:
      image: "microsoft/mssql-server-linux"
      environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    #frontend:
      #build: ./frontend
      #ports:
        #- "5001:80"
